name: 🚨 Checks

on:
  push:
    branches:
      -  main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  test:
    name: 🧪 Test
    runs-on: macos-13

    steps:
      - name: 🗄️ Checkout Code
        uses: actions/checkout@v3
      - name: 🧰 Select Xcode Version
        run: sudo xcode-select -s "/Applications/Xcode_15.0.app/Contents/Developer"
      - name: 🧪 Run tests
        run: xcodebuild test -workspace "SwiftNibbles.xcworkspace" -scheme "swift-nibbles-Package" -testPlan "swift-nibbles-Package" -destination "OS=17.0,name=iPhone 15 Pro"
      - name: 📊 Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          swift: true
