name: 🚨 Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 🧪 Test
    runs-on: macos-13

    steps:
      - name: 🗄️ Checkout Code
        uses: actions/checkout@v3
      - name: 🧰 Select Xcode Version
        run: sudo xcode-select -s "/Applications/Xcode_14.3.1.app/Contents/Developer"
      - name: 🧪 Run tests
        run: xcodebuild test -scheme "Nibbles-Package" -testPlan "Nibbles-Package" -destination "OS=16.4,name=iPhone 14 Pro"
      - name: 📊 Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          swift: true
